# Generated by Django 2.0 on 2018-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_image', models.FileField(upload_to='')),
                ('course_author', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField()),
                ('course_description', models.TextField()),
                ('course_language', models.CharField(max_length=255)),
            ],
        ),
    ]
