# Generated by Django 2.0 on 2018-03-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa_hoc', models.CharField(max_length=255)),
                ('anh_cover', models.FileField(upload_to='')),
                ('ngay_tao', models.DateTimeField()),
                ('mieu_ta', models.TextField()),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='link_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='video',
            name='khoa_hoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='courses.KhoaHoc'),
            preserve_default=False,
        ),
    ]
