# Generated by Django 2.0 on 2018-03-15 19:30

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('courses', '0003_auto_20180316_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='category',
            name='KhoaHoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='courses.KhoaHoc'),
        ),
    ]
