# Generated by Django 2.0 on 2018-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180316_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='KhoaHoc',
        ),
        migrations.AddField(
            model_name='category',
            name='khoa_hoc',
            field=models.ManyToManyField(to='courses.KhoaHoc'),
        ),
    ]
