# Generated by Django 2.0 on 2018-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180316_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='so_hoc_sinh',
            field=models.IntegerField(default=0),
        ),
    ]
