# Generated by Django 2.0 on 2018-03-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_khoahoc_so_hoc_sinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khoahoc',
            name='so_hoc_sinh',
        ),
    ]
