# Generated by Django 2.1.7 on 2019-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='anh_cover',
            field=models.FileField(blank=True, upload_to='cover/'),
        ),
    ]
